Repository WorkQuest/Front-end-DAO, pull requests merged in 2022-04, with the labels that each got.

#49 fix/24255/profile-edit-&-validation fixed validation in profile
  locales/en.json
  pages/profile.vue
Labels: Check needed!

#61 feature/24255/profile-edit-&-validation
  pages/profile.vue
Labels: Check needed!, Important!

#55 fix/25984/delegate-fix fixed undelegate modal
  components/CtmModal/CtmModalDelegate/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  components/CtmModal/CtmModalUndelegate/index.vue
  components/mobile/TableItem.vue
  components/ui/BaseTable/index.vue
  locales/en.json
  pages/investors/_id/index.vue
  pages/investors/index.vue
  pages/wallet.vue
  store/wallet/getters.js
  utils/wallet.js
Labels: Check needed!, Important!

#63 Fix/21618/modals refactoring
  components/CtmModal/CtmModalAddCard/index.vue
  components/CtmModal/CtmModalAddCase/index.vue
  components/CtmModal/CtmModalAddDiscussion/index.vue
  components/CtmModal/CtmModalAddLiquidity/index.vue
  components/CtmModal/CtmModalApplyForAPension/index.vue
  components/CtmModal/CtmModalAreYouSure/index.vue
  components/CtmModal/CtmModalCardHasBeenAdded/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalConfirmDetails/index.vue
  components/CtmModal/CtmModalCreditingDeposit/index.vue
  components/CtmModal/CtmModalDeposit/index.vue
  components/CtmModal/CtmModalDisableTwoFA/index.vue
  components/CtmModal/CtmModalGallery/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalInsureCase/index.vue
  components/CtmModal/CtmModalInvitation/index.vue
  components/CtmModal/CtmModalInviteSend/index.vue
  components/CtmModal/CtmModalMakeDeposit/index.vue
  components/CtmModal/CtmModalMessageSend/index.vue
  components/CtmModal/CtmModalNotice/index.vue
  components/CtmModal/CtmModalOpenADeposit/index.vue
  components/CtmModal/CtmModalOpenADispute/index.vue
  components/CtmModal/CtmModalPrivacy/index.vue
  components/CtmModal/CtmModalQuestAgreed/index.vue
  components/CtmModal/CtmModalQuestCreated/index.vue
  components/CtmModal/CtmModalRaiseViews/index.vue
  components/CtmModal/CtmModalRemoveLiquidity/index.vue
  components/CtmModal/CtmModalRequestSend/index.vue
  components/CtmModal/CtmModalRestore/index.vue
  components/CtmModal/CtmModalReviewEmployer/index.vue
  components/CtmModal/CtmModalSecurityCheck/index.vue
  components/CtmModal/CtmModalSendARequest/index.vue
  components/CtmModal/CtmModalShowFile/index.vue
  components/CtmModal/CtmModalSignWorkQuest/index.vue
  components/CtmModal/CtmModalSkills/index.vue
  components/CtmModal/CtmModalStatus/index.vue
  components/CtmModal/CtmModalThanksSend/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  components/CtmModal/CtmModalTransactionSend/index.vue
  components/CtmModal/CtmModalTransfer/index.vue
  components/CtmModal/CtmModalTwoFAAuth/index.vue
  components/CtmModal/CtmModalWarning/index.vue
  components/CtmModal/CtmModalWelcome/index.vue
  components/CtmModal/CtmModalWithdraw/index.vue
  components/CtmModal/CtmModalWithdrawAbout/index.vue
  components/CtmModal/index.vue
  pages/profile.vue
  store/modals/modals.js
Labels: in progress

#65 Fix/25984/delegate fix 2 fixed rules for open modal add proposal
  pages/proposals/index.vue
  store/wallet/actions.js
Labels: Check needed!

#66 fix/21618/modals-refactoring small transaction modal fix
  pages/wallet.vue
Labels: Check needed!

#62 feature/26888/cookies-authorization
  middleware/auth.js
  pages/confirm.vue
  pages/index.vue
  pages/role.vue
  pages/sign-in.vue
  plugins/axios.js
  store/user/actions.js
  store/user/getters.js
  store/user/mutations.js
Labels: in progress

#58 Feature/26043/hex to bech32
  abi/WQVoting.js
  abi/index.js
  components/CtmModal/CtmModalAddProposal/index.vue
  components/CtmModal/CtmModalChangePercent/index.vue
  components/CtmModal/CtmModalConfirmDetails/index.vue
  components/CtmModal/CtmModalDelegate/index.vue
  components/CtmModal/CtmModalDeposit/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalInsureCase/index.vue
  components/CtmModal/CtmModalOpenADeposit/index.vue
  components/CtmModal/CtmModalOpenADispute/index.vue
  components/CtmModal/CtmModalPrivacy/index.vue
  components/CtmModal/CtmModalRestore/index.vue
  components/CtmModal/CtmModalSecurityCheck/index.vue
  components/CtmModal/CtmModalSignWorkQuest/index.vue
  components/CtmModal/CtmModalTransactionReceipt/index.vue
  components/CtmModal/CtmModalTwoFAAuth/index.vue
  components/CtmModal/CtmModalUndelegate/index.vue
  components/CtmModal/CtmModalWithdraw/index.vue
  components/ui/BaseTable/index.vue
  package.json
  pages/discussions/_id/index.vue
  pages/investors/_id/index.vue
  pages/proposals/_id/index.vue
  pages/sign-in.vue
  pages/sign-up.vue
  pages/wallet.vue
  plugins/main.js
  plugins/vee-validate.js
  store/wallet/actions.js
  utils/enums.js
  utils/wallet.js
Labels: Check needed!

#64 fix/25343/sign-in_adaptive fix styles for class "template"
  assets/img/app/auth_bg.png
  assets/img/app/auth_proposals-bg.svg
  layouts/auth.vue
  locales/en.json
  pages/sign-in.vue
Labels: Check needed!

#69 fix/26100/update-counter-comment
  pages/discussions/_id/index.vue
Labels: Check needed!

#70 fix/26118/fix-avatar
  components/app/Pages/Discussions/CommentField.vue
  components/app/Pages/Discussions/RootCommentField.vue
  components/ui/DiscussionCard/index.vue
  pages/discussions/_id/index.vue
Labels: Check needed!

#67 feature/27727 Change account confirmation logic
  components/CtmModal/CtmModalPrivacy/index.vue
  middleware/auth.js
  pages/confirm.vue
  pages/role.vue
  pages/sign-in.vue
  utils/enums.js
Labels: Check needed!

#72 fix/26112/responsive-favorites-button fixed favorite btn
  components/ui/DiscussionCard/index.vue
Labels: Check needed!
