Repository WorkQuest/Front-end-DAO, pull requests merged in 2022-07, with the labels that each got.

#98 fix: fix text after confirm registration
  locales/en.json
Labels: Ready for review

#113 fix: deleted unused images
  assets/img/app/WORK_QUEST_logo_horizontal.png
  assets/img/app/about.png
  assets/img/app/account.png
  assets/img/app/account_left.png
  assets/img/app/account_right.png
  assets/img/app/auth_bg.svg
  assets/img/app/bg_login_top.png
  assets/img/app/box_left_create.png
  assets/img/app/close.png
  assets/img/app/create_bg_m.png
  assets/img/app/fake_profile.png
  assets/img/app/fake_quote.png
  assets/img/app/fakeavatar.svg
  assets/img/app/fakeavatarcomp.svg
  assets/img/app/hands.png
  assets/img/app/logo_long.svg
  assets/img/app/next-page.png
  assets/img/app/next-page_blue.png
  assets/img/app/sign-up_bg.png
  assets/img/app/widget_left.png
  assets/img/app/widget_right.png
  assets/img/ui/arrow-down.svg
  assets/img/ui/arrowRight.svg
  assets/img/ui/arrow_down_grey.png
  assets/img/ui/banner_left.png
  assets/img/ui/burger_menu_.svg
  assets/img/ui/cards.svg
  assets/img/ui/chart.svg
  assets/img/ui/compass.png
  assets/img/ui/document.svg
  assets/img/ui/doubleLeft.svg
  assets/img/ui/doubleRight.svg
  assets/img/ui/download.svg
  assets/img/ui/filter.png
  assets/img/ui/hromb-logo.svg
  assets/img/ui/location.png
  assets/img/ui/mail.png
  assets/img/ui/rectangle.svg
  assets/img/ui/refresh-button.png
Labels: Ready for review

#114 fix/33780/dao-fixes
  components/CtmModal/CtmModalAddProposal/index.vue
  components/CtmModal/CtmModalDelegate/index.vue
  components/app/Pages/Discussions/CommentFooter.vue
  components/mobile/TableItem.vue
  components/ui/BaseImages/index.vue
  components/ui/DiscussionCard/index.vue
  package.json
  pages/discussions/_id/index.vue
  pages/investors/_id/index.vue
  pages/profile.vue
  plugins/main.js
Labels: in progress

#104 fix: fix display verification info
  pages/investors/_id/index.vue
Labels: Ready for review

#120 fix: added data-selector
  components/ui/CreateWallet/index.vue
Labels: Ready for review

#121 fix/34037/cookies-lifetime
  components/CtmModal/CtmModalPrivacy/index.vue
  layouts/auth.vue
  pages/sign-in.vue
  pages/sign-up.vue
  pages/wallet.vue
  store/user/actions.js
  store/user/mutations.js
  utils/constants/cookiesLifetime.js
Labels: Check needed!

#125 update/34037/path-root changed base path to path.root
  layouts/auth.vue
  pages/sign-in.vue
  pages/sign-up.vue
  store/user/actions.js
  store/user/mutations.js
Labels: Check needed!

#136 fix: check validation in discussion
  components/app/Pages/Discussions/CommentFooter.vue
Labels: Ready for review

#140 Fix/34748/validator address and rewards
  components/CtmModal/CtmModalDelegate/index.vue
  components/CtmModal/CtmModalGiveTransfer/index.vue
  components/CtmModal/CtmModalSecurityCheck/index.vue
  components/CtmModal/CtmModalUndelegate/index.vue
  components/ui/BaseButton/index.vue
  components/ui/BaseTable/index.vue
  locales/en.json
  nuxt.config.js
  pages/validators/_id/index.vue
  pages/validators/index.vue
  plugins/axiosNode.js
  plugins/vee-validate.js
  store/validators/actions.js
  utils/constants/validators.js
  utils/wallet.js
Labels: Check needed!
